In [2]:
import pandas as pd
import sqlite3 as sql

Foydali buyruqlar

In [5]:
url = "https://github.com/anvarnarz/praktikum_datasets/raw/main/electricity.db"
# url = "https://www.sqlitetutorial.net/wp-content/uploads/2018/03/chinook.zip"
## Agfara Google Colabda ishlashangiz keyingi 2 qatorni ishga tushuring
# !wget url
# !unzip "chinook.zip"

## Agar shaxsiy kompyuterda, Jupyter Notebookda ishlasangiz keyingi 4 qatorni ishga tushuring
from urllib.request import urlretrieve
import shutil
urlretrieve(url, "fayllar/electricity.db") # faylni yuklab olish
# shutil.unpack_archive("chinook.zip") # zip faylni ochish

('fayllar/electricity.db', <http.client.HTTPMessage at 0x21ab60d9790>)

In [6]:
db = sql.connect('fayllar/electricity.db')
cursor = db.cursor()

In [8]:
query = "SELECT name FROM sqlite_master WHERE type='table';"
cursor.execute(query)
cursor.fetchall()

[('elect',)]

In [10]:
query = "PRAGMA table_info(elect);"
cursor.execute(query)
cursor.fetchall()

[(0, 'index', 'INTEGER', 0, None, 0),
 (1, 'country', 'TEXT', 0, None, 0),
 (2, 'code', 'TEXT', 0, None, 0),
 (3, 'year', 'INTEGER', 0, None, 0),
 (4, 'coal', 'REAL', 0, None, 0),
 (5, 'gas', 'REAL', 0, None, 0),
 (6, 'hydro', 'REAL', 0, None, 0),
 (7, 'renewable_other', 'REAL', 0, None, 0),
 (8, 'solar', 'REAL', 0, None, 0),
 (9, 'oil', 'REAL', 0, None, 0),
 (10, 'wind', 'REAL', 0, None, 0),
 (11, 'nuclear', 'REAL', 0, None, 0)]

In [12]:
query = "SELECT * FROM elect LIMIT 15;"
pd.read_sql(query, db, index_col='index')

,country,code,year,coal,gas,hydro,renewable_other,solar,oil,wind,nuclear
index,,,,,,,,,,,
0,Afghanistan,AFG,2000,0.0,0.155,0.312,0.0,0.0000,0.0,0.00000,0.0
1,Afghanistan,AFG,2001,0.0,0.094,0.498,0.0,0.0000,0.0,0.00000,0.0
2,Afghanistan,AFG,2002,0.0,0.132,0.555,0.0,0.0000,0.0,0.00000,0.0
3,Afghanistan,AFG,2003,0.0,0.309,0.630,0.0,0.0000,0.0,0.00000,0.0
4,Afghanistan,AFG,2004,0.0,0.329,0.565,0.0,0.0000,0.0,0.00000,0.0
5,Afghanistan,AFG,2005,0.0,0.344,0.590,0.0,0.0000,0.0,0.00000,0.0
6,Afghanistan,AFG,2006,0.0,0.200,0.637,0.0,0.0000,0.0,0.00000,0.0
7,Afghanistan,AFG,2007,0.0,0.198,0.748,0.0,0.0000,0.0,0.00000,0.0
8,Afghanistan,AFG,2008,0.0,0.186,0.542,0.0,0.0000,0.0,0.00001,0.0
9,Afghanistan,AFG,2009,0.0,0.162,0.776,0.0,0.0000,0.0,0.00010,0.0
10,Afghanistan,AFG,2010,0.0,0.185,0.751,0.0,0.0002,0.0,0.00010,0.0
11,Afghanistan,AFG,2011,0.0,0.252,0.595,0.0,0.0002,0.0,0.00010,0.0
12,Afghanistan,AFG,2012,0.0,0.174,0.710,0.0,0.0280,0.0,0.00000,0.0
13,Afghanistan,AFG,2013,0.0,0.218,0.855,0.0,0.0300,0.0,0.00000,0.0
14,Afghanistan,AFG,2014,0.0,0.154,0.968,0.0,0.0320,0.0,0.00000,0.0

In [16]:
query = "SELECT DISTINCT country FROM elect;" # takrorlanuvchi qiymatlarni tashlab yuboradi
davlatlar = pd.read_sql(query,db)

In [18]:
'Uzbekistan' in davlatlar['country'].values # malum bir datafram ichidan biron qiymat bor yoqligini tekshirish uchun ishlatiladi

True

In [19]:
query = "SELECT * FROM elect WHERE country = 'Uzbekistan';"
dfuz = pd.read_sql(query, db)
dfuz

,index,country,code,year,coal,gas,hydro,renewable_other,solar,oil,wind,nuclear
0,5964,Uzbekistan,UZB,2000,11.602405,25.523451,5.817000,0.0,0.000000,1.380143,0.0,0.0
1,5965,Uzbekistan,UZB,2001,11.766320,25.884038,5.899000,0.0,0.000000,1.399642,0.0,0.0
2,5966,Uzbekistan,UZB,2002,12.214374,26.869686,6.124000,0.0,0.000000,1.452939,0.0,0.0
3,5967,Uzbekistan,UZB,2003,11.833513,26.031852,7.544000,0.0,0.000000,1.407634,0.0,0.0
4,5968,Uzbekistan,UZB,2004,11.595776,25.508869,8.920000,0.0,0.000000,1.379355,0.0,0.0
5,5969,Uzbekistan,UZB,2005,11.490919,25.278199,8.838000,0.0,0.000000,1.366882,0.0,0.0
6,5970,Uzbekistan,UZB,2006,11.827788,26.019258,4.653000,0.0,0.000000,1.406953,0.0,0.0
7,5971,Uzbekistan,UZB,2007,12.051665,26.511751,4.610000,0.0,0.000000,1.433584,0.0,0.0
8,5972,Uzbekistan,UZB,2008,10.774273,23.701692,4.443000,0.0,0.000000,1.281634,0.0,0.0
9,5973,Uzbekistan,UZB,2009,9.084625,28.017530,6.418000,0.0,0.000000,1.080645,0.0,0.0
10,5974,Uzbekistan,UZB,2010,9.792027,30.199200,8.110000,0.0,0.000000,1.164793,0.0,0.0
11,5975,Uzbekistan,UZB,2011,10.534094,32.487781,5.646000,0.0,0.000000,1.253064,0.0,0.0
12,5976,Uzbekistan,UZB,2012,10.365016,31.966333,6.586000,0.0,0.000000,1.232952,0.0,0.0
13,5977,Uzbekistan,UZB,2013,10.939346,33.737603,5.647000,0.0,0.001996,1.301270,0.0,0.0
14,5978,Uzbekistan,UZB,2014,11.112674,34.272157,6.014000,0.0,0.002046,1.321888,0.0,0.0
15,5979,Uzbekistan,UZB,2015,10.519789,35.780629,6.998000,0.0,0.002176,1.251363,0.0,0.0
16,5980,Uzbekistan,UZB,2016,10.783891,36.678911,7.254000,0.0,0.004643,1.282778,0.0,0.0
17,5981,Uzbekistan,UZB,2017,10.998707,37.409561,8.343000,0.0,0.006290,1.308332,0.0,0.0
18,5982,Uzbekistan,UZB,2018,11.853192,40.315893,5.838030,0.0,0.006827,1.409975,0.0,0.0
19,5983,Uzbekistan,UZB,2019,12.297660,41.827647,5.451373,0.0,0.006827,1.462846,0.0,0.0
20,5984,Uzbekistan,UZB,1985,NaN,NaN,5.431443,0.0,0.000000,NaN,0.0,0.0
21,5985,Uzbekistan,UZB,1986,NaN,NaN,4.618273,0.0,0.000000,NaN,0.0,0.0
22,5986,Uzbekistan,UZB,1987,NaN,NaN,6.770521,0.0,0.000000,NaN,0.0,0.0
23,5987,Uzbekistan,UZB,1988,NaN,NaN,7.163847,0.0,0.000000,NaN,0.0,0.0
24,5988,Uzbekistan,UZB,1989,NaN,NaN,5.502153,0.0,0.000000,NaN,0.0,0.0
25,5989,Uzbekistan,UZB,1990,NaN,NaN,6.648000,0.0,0.000000,NaN,0.0,0.0
26,5990,Uzbekistan,UZB,1991,NaN,NaN,6.031000,0.0,0.000000,NaN,0.0,0.0
27,5991,Uzbekistan,UZB,1992,NaN,NaN,6.281000,0.0,0.000000,NaN,0.0,0.0
28,5992,Uzbekistan,UZB,1993,NaN,NaN,7.358000,0.0,0.000000,NaN,0.0,0.0
29,5993,Uzbekistan,UZB,1994,NaN,NaN,7.156000,0.0,0.000000,NaN,0.0,0.0
30,5994,Uzbekistan,UZB,1995,NaN,NaN,6.188000,0.0,0.000000,NaN,0.0,0.0
31,5995,Uzbekistan,UZB,1996,NaN,NaN,6.525000,0.0,0.000000,NaN,0.0,0.0
32,5996,Uzbekistan,UZB,1997,NaN,NaN,5.777000,0.0,0.000000,NaN,0.0,0.0
33,5997,Uzbekistan,UZB,1998,NaN,NaN,5.758000,0.0,0.000000,NaN,0.0,0.0
34,5998,Uzbekistan,UZB,1999,NaN,NaN,5.692000,0.0,0.000000,NaN,0.0,0.0